# Generated by Django 6.0.2 on 2026-03-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/videos/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('hero', 'Hero'), ('campaign', 'Campagne'), ('testimonial', 'Témoignage'), ('event', 'Événement'), ('general', 'Général')], default='general', max_length=20)),
                ('thumbnail', models.ImageField(blank=True, upload_to='uploads/thumbnails/')),
                ('is_published', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='imageasset',
            name='category',
            field=models.CharField(choices=[('hero', 'Hero'), ('founder', 'Fondateur'), ('partner', 'Partenaire'), ('about', 'À propos'), ('event', 'Événement'), ('general', 'Général')], default='general', max_length=20),
        ),
    ]
