# Generated by Django 6.0.2 on 2026-03-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_eventimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageasset',
            name='category',
            field=models.CharField(choices=[('hero', 'Hero'), ('founder', 'Fondateur'), ('partner', 'Partenaire'), ('about', 'À propos'), ('general', 'Général')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='videoasset',
            name='category',
            field=models.CharField(choices=[('hero', 'Hero'), ('campaign', 'Campagne'), ('testimonial', 'Témoignage'), ('general', 'Général')], default='general', max_length=20),
        ),
    ]
