# Generated by Django 6.0.2 on 2026-03-28 20:43

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_imageasset_category_alter_videoasset_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='file',
            field=models.ImageField(upload_to='uploads/events/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp']), api.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='file',
            field=models.ImageField(upload_to='uploads/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp']), api.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='videoasset',
            name='file',
            field=models.FileField(upload_to='uploads/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'webm']), api.models.validate_video_file_size]),
        ),
        migrations.AlterField(
            model_name='videoasset',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='uploads/thumbnails/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp']), api.models.validate_image_file_size]),
        ),
    ]
