
FROM node:22-alpine

WORKDIR /app

RUN npm install -g @angular/cli

COPY package.json package-lock.json* ./

RUN --mount=type=cache,target=/root/.npm npm install

COPY . .

EXPOSE 4200

CMD ["npm", "start", "--", "--host=0.0.0.0"]
